# 아래의 주요 key, secret은 쿠버네티스의 secret 자원을 사용하여 실행 시점에 대체

server:
  port: 8080
spring:
#  config:
#    activate:
#      on-profile: local
  redis:
  # 아래 REDIS_HOST는 deployment에서 정의한 env변수명과 일치해야함
    host: ${REDIS_HOST}
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}/ordersystem
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true

logging:
  level:
    root: info

jwt:
  expiration: 30
  secretKey: my_token_secret
  expirationRt: 14400
  secretKeyRt: hackerton_secret

# asw s3 설정
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: junghahwang