apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: natural
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jeongha61@naver.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: junghahwang-com-tls
  namespace: natural
spec: 
  secretName: junghahwang-com-tls
  duration: 2160h
  renewBefore: 360h 
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: server.jungha.store
  dnsNames:
  - server.jungha.store
